In [3]:
import pandas as pd

In [5]:
df = pd.read_csv("amazon_products.csv")

df.head()

         ASIN                          Product_Name  Reviews   Price
0  B07X6GNBNT                      Credit Card Bill   393124    10.0
1  B097GR45SS          Safari Pentagon Pro 8 Wheels    35066  1999.0
2  B0F67J5S83        Safari Cabin Genius Alley 55cm     6454  1299.0
3  B082F88NKP      Billebon Premium Neck Pillow for    15020   189.0
4  B0BL11Q9D3  Kamiliant American Tourister Harrier    15122  1199.0

# rank top 100 products by volume (quantity)

In [6]:
top_volume = df.sort_values(
    by="Reviews",
    ascending=False
)

top_volume.head(100)

           ASIN                            Product_Name  Reviews    Price
193  B071Z8M4KX    Boat BassHeads 100 in-Ear Headphones   434782   449.00
0    B07X6GNBNT                        Credit Card Bill   393124    10.00
136  B005FYNT3G               SANDISK Cruzer Blade 32GB   273138   739.00
181  B0FBRGKXHG      OnePlus Bullets Wireless Z3 in-Ear   230008  1799.00
200  B0000C73CQ     Fujifilm Instax Mini Picture Format   213344  3190.00
..          ...                                     ...      ...      ...
230  B071CMQ6N2  YouBella Jewellery Bracelets for Women    13301   142.00
443  B0B8RSTZ4V              Boldfit Wrist Band for Gym    13296   170.05
36   B097RJ22Q3        Lavie Sport Polyester Lino Wheel    13011   987.00
313  B0GMWDK829           UTECTION by VOOK Wireless Mic    12926  2299.00
515  B084HCJ1VT               Toyshine 120 Pcs 12 Color    12651   169.00

[100 rows x 4 columns]

In [12]:
top_volume.head(100).to_csv(
    "top_100_by_volume.csv",
    index=False
)

# rank top 100 products by value

In [9]:
df["Estimated_Value"] = df["Reviews"] * df["Price"]

In [10]:
top_value = df.sort_values(
    by="Estimated_Value",
    ascending=False
)

top_value.head(100)

,ASIN,Product_Name,Reviews,Price,Estimated_Value
200,B0000C73CQ,Fujifilm Instax Mini Picture Format,213344,3190.0,680567360.0
162,B08ZJG6TVT,Seagate Expansion 2TB External HDD,32612,12699.0,414139788.0
181,B0FBRGKXHG,OnePlus Bullets Wireless Z3 in-Ear,230008,1799.0,413784392.0
145,B00A0VCJPI,TP-Link TL-WA850RE N300 Wireless Range,204260,1549.0,316398740.0
154,B094QZLJQ6,Seagate One Touch 2Tb External,21048,12999.0,273602952.0
...,...,...,...,...,...
130,B0DNFSSF3F,SANDISK Ultra Dual Drive Go,4237,1949.0,8257913.0
164,B08CYNJ5KY,HP 682 Black Original Ink,8050,1025.0,8251250.0
70,B09J171VHQ,Jockey 1722 Women's Wirefree Non,16182,499.0,8074818.0
490,B00ADZUNYK,Little's Junior Ring (Plastic,50391,159.0,8012169.0
19,B07M9BRCQ5,Fur Jaden Brown Textured Leatherette,12169,649.0,7897681.0

In [11]:
top_value.head(100).to_csv(
    "top_100_by_value.csv",
    index=False
)